# -*- coding: utf-8 -*-
"""FYSC 23 comp project 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDUJACf2txlI6eMgIzi3nxfAxUDhMveo
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameters
t_max = 20
time_steps = 201
times = np.linspace(0, t_max, time_steps)
L = 6          # Length of chain
V = 1.0        # Hopping amplitude

for Delta in [+2.0, -2.0]:
    # Initial, unperturbed Hamiltonian
    H0 = np.zeros((L,L))
    for i in range(L):
        if i > 0:
            H0[i,i-1] = V
        if i < L-1:
            H0[i,i+1] = V

    # Diagonalize H0 to get initial eigenvalues and eigenvectors
    E0, U0 = np.linalg.eigh(H0)

    # Perturbed Hamiltonian after t=0 (site 1 has Delta energy)
    H_pert = H0.copy()
    H_pert[0,0] += Delta

    # Diagonalize H_pert to get eigenvalues and eigenvectors
    E_pert, U_pert = np.linalg.eigh(H_pert)

    # Initially, ground state in the lowest eigenstate of H0
    psi0 = U0[:,0]  # Initial wave function (column vector in site basis)

    # Express initial state in perturbed basis
    c_m = U_pert.T @ psi0

    # Prepare array for time-dependent site densities
    n_t = np.zeros((L, time_steps))

    for k, t in enumerate(times):
        # Evolve in perturbed basis & transform back to site basis
        psi_t = U_pert @ (c_m * np.exp(-1j * E_pert * t))
        n_t[:,k] = np.abs(psi_t)**2

    plt.figure()
    for i in range(L):
        plt.plot(times, n_t[i], label=f'Site {i+1}')
    plt.xlabel('Time')
    plt.ylabel('Particle density')
    plt.title(f'Time-dependent site densities, Δ = {Delta}')
    plt.legend()
    plt.tight_layout()
    plt.show()

import numpy as np
import matplotlib.pyplot as plt


u = [0, 15, 15, 15, 15, 15]
V = -1
delta_1 = 5
delta_2 = 15
times = np.linspace(0, 20, 2000)
epsilon = [-15, 0, 0, 0, 0, 0]

L = 6

def Two_electron_Hamiltonian(L, epsilon, u):
    dim = L*L
    H = np.zeros((dim, dim), dtype=float)
    for i_up in range(L):
        for i_down in range(L):
            idx = i_up * L + i_down
            # Interaction
            on_site_energy = epsilon[i_up] + epsilon[i_down]
            H[idx, idx] = on_site_energy + (u[i_up] if i_up == i_down else 0)
            # Spin-up hopping
            for delta in [-1, 1]:
                j_up = i_up + delta
                if 0 <= j_up < L:
                    H[idx, j_up * L + i_down] = V
            # Spin-down hopping
            for delta in [-1, 1]:
                j_down = i_down + delta
                if 0 <= j_down < L:
                    H[idx, i_up * L + j_down] = V
    return H

def simulate_and_plot(delta):

    H0 = Two_electron_Hamiltonian(L, epsilon, u)

    E0, U0 = np.linalg.eigh(H0)
    psi0 = U0[:, 0] / np.linalg.norm(U0[:, 0])
    n_up_t = np.zeros((L, len(times)))
    d_t = np.zeros((L, len(times)))
    for idx, t in enumerate(times):
        theta_t = 1 if t > 0 else 0
        epsilon_jump = [epsilon[0] + theta_t * delta] + epsilon[1:]
        H = Two_electron_Hamiltonian(L, epsilon_jump, u)
        E, U = np.linalg.eigh(H)
        c_m = U.conj().T @ psi0
        psi_t = U @ (c_m * np.exp(-1j * E * t))
        for site in range(L):
            n_up_t[site, idx] = np.sum(np.abs(psi_t[site*L:(site+1)*L])**2)
            d_t[site, idx] = np.abs(psi_t[site*L + site])**2


    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    for i in range(L):
        plt.plot(times, n_up_t[i], label=f'Site {i+1}')
    plt.title(f'Spin-up electron density, Δ = {delta}')
    plt.xlabel('Time')
    plt.ylabel('Density n_up')
    plt.legend()
    plt.subplot(1, 2, 2)
    for i in range(L):
        plt.plot(times, d_t[i], label=f'Site {i+1}')
    plt.title(f'Double occupancy, Δ = {delta}')
    plt.xlabel('Time')
    plt.ylabel('Double occupancy d')
    plt.legend()
    plt.tight_layout()
    plt.show()


simulate_and_plot(delta_1)
simulate_and_plot(delta_2)



def simulate_density(delta):
    """Simulate for a given Δ and return the densities."""
    H0 = Two_electron_Hamiltonian(L, epsilon, u)
    E0, U0 = np.linalg.eigh(H0)
    psi0 = U0[:, 0] / np.linalg.norm(U0[:, 0])

    n_up_t = np.zeros((L, len(times)))
    d_t = np.zeros((L, len(times)))

    for idx, t in enumerate(times):
        theta_t = 1 if t > 0 else 0
        epsilon_jump = [epsilon[0] + theta_t * delta] + epsilon[1:]
        H = Two_electron_Hamiltonian(L, epsilon_jump, u)
        E, U = np.linalg.eigh(H)
        c_m = U.conj().T @ psi0
        psi_t = U @ (c_m * np.exp(-1j * E * t))
        for site in range(L):
            n_up_t[site, idx] = np.sum(np.abs(psi_t[site*L:(site+1)*L])**2)
            d_t[site, idx] = np.abs(psi_t[site*L + site])**2

    return n_up_t, d_t



site = [0,1,2,3,4,5]  # choose site 0–5

deltas = [20,20.5,21,21.5,22,22.5,23,23.5,24,24.5,25]

for s in site:
    plt.figure(figsize=(8, 4))
    for delta in deltas:
        n_up, d = simulate_density(delta)
        density_difference = np.abs(n_up[s] - d[s])
        plt.plot(times, density_difference, label=f'Δ={delta}')
    plt.title(f"Density difference at site {s+1}")
    plt.xlabel("Time")
    plt.ylabel(r"$|\rho_n^{(2)}(t) - \rho_{n\uparrow}(t)|$")
    plt.legend(ncol=2, fontsize=8)
    plt.tight_layout()
    plt.show()